spring:
  data:
    mongodb:
      uri: mongodb+srv://eedb:admin@cluster0-3mgem.gcp.mongodb.net/test?retryWrites=true&w=majority
      database: election_essentials
    rest:
      base-path: /api

server: 
  port: 5000
